# Generated by Django 5.0.6 on 2024-05-09 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='thumb',
            field=models.ImageField(upload_to='media'),
        ),
    ]
